### ISSUE TITLE
Course Adoption

### ISSUE THREAD

**Issue by waqarsaleem** [SuprDewd/T-414-AFLV#3]
I am a CS professor at Habib University, Pakistan, teaching a course on Competitive Programming for the first time, following encouraging participation in local ICPC rounds by our students for the past 3 years. I found several courses online but yours was the simplest and clearest to follow. Thank you for making all the material freely available. I am following CP Book 4. The seance of topics is similar to your lectures so maybe you followed the same, or a previous edition. In any case, thank you.

I am writing this as you asked to be informed if anyone adopts your course.

**Comment by SuprDewd** [comment]
Thank you Waqar! Really appreciate hearing about this and hope your course goes well.
